filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: false
  paths:
    - /var/log/*.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
output.elasticsearch:
  hosts: 
   {% for host in salt['pillar.get']('es_outputs:hosts') -%}
   - {{ host }}
   {% endfor -%}
  api_key: {{ pillar['es_outputs']['api_key'] }}

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
